import os
import time

i = 1
print(i , ". ------------------------------------>")
os.system("pip install pygame")
print("\n")
print(i+1 , ". ------------------------------------>")
os.system("pip install telebot")
print("\n")
print(i+2 , ". ------------------------------------>")
os.system("pip install socket")
print("\n")
print(i+3 , ". ------------------------------------>")
os.system("pip install Django")
print("\n")
print(i+4 , ". ------------------------------------>")
os.system("pip install Flask")
print("\n")
print(i+5 , ". ------------------------------------>")
os.system("pip install more-itretools")
print("\n")
print(i+6 , ". ------------------------------------>")
os.system("pip install netifaces")
print("\n")
print(i+7 , ". ------------------------------------>")
os.system("pip install numpy")
print("\n")
print(i+8 , ". ------------------------------------>")
os.system("pip install openpyxl")
print("\n")
print(i+9 , ". ------------------------------------>")
os.system("pip install pillow")
print("\n")
print(i+10 , ". ------------------------------------>")
os.system("pip install pygame")
print("\n")
print(i+11 , ". ------------------------------------>")
os.system("pip install pyinstaller")
print("\n")
print(i+12 , ". ------------------------------------>")
os.system("pip install pymysql")
print("\n")
print(i+13, ". ------------------------------------>")
os.system("pip install pyqt5")
print("\n")
print(i+14, ". ------------------------------------>")
os.system("pip install pysocks")
print("\n")
print(i+15, ". ------------------------------------>")
os.system("pip install pyTelegramBotAPI")
print("\n")
print(i+16, ". ------------------------------------>")
os.system("pip install pytest")
print("\n")
print(i+17, ". ------------------------------------>")
os.system("pip install selenium")
print("\n")
print(i+18, ". ------------------------------------>")
os.system("pip install setuptools")
print("\n")
print(i+19, ". ------------------------------------>")
os.system("pip install telegram")
print("\n")
print(i+20, ". ------------------------------------>")
os.system("pip install watchdog")
print("\n")
print(i+21, ". ------------------------------------>")
os.system("pip install requests")
print("\n")
print(i+22, ". ------------------------------------>")
os.system("pip install beautifulsoup4")
print("\n")
print(i+23, ". ------------------------------------>")
os.system("pip install bs4")
print("\n")
print(i+24, ". ------------------------------------>")
os.system("pip install http-status")
print("\n")
print(i+25, ". ------------------------------------>")
os.system("pip install django-http-status")
print("\n")
print(i+26, ". ------------------------------------>")
os.system("pip install webdriver-manager")
print("\n")
print(i+27, ". ------------------------------------>")
os.system("pip install lxml")
print("\n")
print(i+28, ". ------------------------------------>")
os.system("pip install openai")
print("\n")
print(i+29, ". ------------------------------------>")
os.system("pip install openai==0.28")
print("\n")
print(i+30, ". ------------------------------------>")
os.system("pip install --upgrade openai")
print("\n")


#-------------------------------------------------------------------------
print("\n")
print("\n")
print("\n")
print("-------------- finish ---------------")
time.sleep(30)